version: '3.8'
services:

  # Docker connection string for local machine: postgres://postgres:postgres@localhost:5432/
  apollo:
    build:
      dockerfile: ./dockerfile
    entrypoint: ./entrypoint.sh
    depends_on: 
     - postgresdb
    ports:
      - 3000:3000
    networks:         
     - hackernews-network
  postgresdb:
    image: postgres:13.5    
    restart: always
    environment:            
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:                
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:         
     - hackernews-network
networks: 
  hackernews-network:
volumes:
  postgres: